import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  subsets: ["latin"], // Specify the desired subsets
  weight: ["400", "700"], // Specify desired weights, or omit for variable font
  display: "swap", // Recommended for better performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="garden">
      <body className={`${rubik.className} antialiased`}>{children}</body>
    </html>
  );
}
